# Generated by Django 3.2.9 on 2021-11-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customfields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, default=0, related_name='_customfields_category_parent_+', to='customfields.Category'),
        ),
    ]
