# Generated by Django 3.2.9 on 2021-11-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customfields', '0002_auto_20211116_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_customfields_category_parent_+', to='customfields.Category'),
        ),
    ]
